---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        #encrypt:
          #enabled: false
        git:
          uri: https://github.com/jesusjrcardenas/spring-cloudconfig
          #username:
          #password:
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls-perf
              search-paths:
                - 'station*'
  security:
    user:
      name: admin
      password: admin